apiVersion: v2
name: authz
description: Authz service for ivanoff-bank.
type: application
version: 1.0.0
appVersion: 1.0.1
#dependencies:
#  - name: cert-manager
#    version: v1.13.1
#    repository: https://charts.jetstack.io
#    alias: cert-manager
#    condition: cert-manager.enabled