apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-nginx-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |-
    user nginx;
    worker_processes 4;
    
    events {
    	worker_connections 1024;
    }
    
    pid /var/run/nginx.pid;
    
    http {
    	default_type application/octet-stream;
    
    	log_format nginx_json escape=json '{'
    	'"http_host": "$http_host",'
    	'"remote_addr": "$remote_addr",'
    	'"status":"$status",'
    	'"body_bytes_sent":"$body_bytes_sent",'
    	'"http_user_agent":"$http_user_agent",'
    	'"request_method":"$request_method",'
    	'"request_time":"$request_time",'
    	'"upstream_response_time":"$upstream_response_time"'
    	'}';
    	
    	access_log /dev/stdout nginx_json;
        error_log /dev/stderr warn;
    	sendfile on;
    
    
    	server {
    		listen 80;

    		location / {
    			proxy_pass http://127.0.0.1:5000;
    		}
    		
    		location =/api/v1/authz/health_check {
                        access_log off;
    			proxy_pass http://127.0.0.1:5000;
    		}
    	}
    }