apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authz
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  rules:
  - host: api.ivanoff.smodata.net
    http:
      paths:
      - path: /authz(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: authz-srv
            port:
              number: 80
  tls:
    - hosts:
        - api.ivanoff.smodata.net
      secretName: ivanoff-tls